###
# Login user
# @name loginUser
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username": "anton2",
    "password": "secret"
}

@accessToken = {{loginUser.response.body.access_token}}

###
# Create new account
# @name createAccount
POST {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "currency": "USD"
}

###
# Get account by id
# @name getAccount

@accountId = 114

GET {{baseUrl}}/accounts/{{accountId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
# List all accounts
# @name listAccounts

@page_id = 1
@page_size = 10
GET {{baseUrl}}/accounts?page_id={{page_id}}&page_size={{page_size}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}