###
# Login user
# @name loginUser
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username": "anton2",
    "password": "secret"
}

@accessToken = {{loginUser.response.body.access_token}}

###
# Create new transfer
# @name createTransfer

@fromAccountId = 114
@toAccountId = 112
@amount = 10
@currency = "USD"

POST {{baseUrl}}/transfers
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "from_account_id": {{fromAccountId}},
    "to_account_id": {{toAccountId}},
    "amount": {{amount}},
    "currency": {{currency}}
}