###
# Create new user
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
    "username": "anton2",
    "full_name": "Anton Golosnichenko",
    "email": "anton@icloud.com",
    "password": "secret"
}