###
# Create new user
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
    "username": "anton2",
    "full_name": "Anton Golosnichenko",
    "email": "anton@icloud.com",
    "password": "secret"
}

###
# Login user
# @name loginUser
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username": "anton2",
    "password": "secret"
}

@accessToken = {{loginUser.response.body.access_token}}

###
# Renew token
# @name renewToken

POST {{baseUrl}}/tokens/renew_access
Content-Type: application/json

{
    "refresh_token": "{{loginUser.response.body.refresh_token}}"
}