version: "3.9"

services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=golang
      - POSTGRES_USER=golang
      - POSTGRES_DB=simple_bank
 