name: simplebank

services:
  api:
    build:
      context: ./simplebank
      dockerfile: Dockerfile
    container_name: simplebank-api
    depends_on:
      - postgres
    networks:
      - bank-network
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - DB_SOURCE=postgresql://golang:golang@simplebank-db:5432/simple_bank?sslmode=disable
    entrypoint: ["/app/wait-for.sh", "simplebank-db:5432", "--", "/app/start.sh"]
    command: ["/app/main"]

  postgres:
    image: postgres:15
    container_name: simplebank-db
    networks:
      - bank-network
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=golang
      - POSTGRES_USER=golang
      - POSTGRES_DB=simple_bank

  redis:
    image: redis:7.4.0-alpine
    container_name: simplebank-redis
    ports:
      - 6379:6379
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge
 