apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::141974081788:user/simplebank-github-ci
      username: simplebank-github-ci
      groups:
        - system:masters